# Generated by Django 5.2.12 on 2026-05-01 13:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_chatroom_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('review_type', models.CharField(choices=[('service', 'Đánh giá Dịch vụ'), ('shop', 'Đánh giá Spa')], default='service', max_length=10)),
                ('service', models.CharField(blank=True, max_length=100, null=True)),
                ('rating', models.IntegerField(default=5)),
                ('content', models.TextField()),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('image_urls', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
