# Generated by Django 5.2.12 on 2026-05-01 18:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_review'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_name', models.CharField(default='Gói tiêu chuẩn', max_length=100)),
                ('sessions', models.CharField(default='1 buổi', max_length=50)),
                ('package_description', models.TextField(blank=True, null=True)),
                ('booking_date', models.DateField()),
                ('booking_time', models.TimeField()),
                ('total_price', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Đang Xử Lý', 'Đang Xử Lý'), ('Hoàn Thành', 'Hoàn Thành'), ('Đã Hủy', 'Đã Hủy')], default='Đang Xử Lý', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.service')),
            ],
        ),
    ]
